import type { Lead, Deal, Activity, User, DashboardMetrics } from "./types"

// Mock users
export const mockUsers: User[] = [
  {
    id: "1",
    name: "Sarah Johnson",
    email: "sarah@company.com",
    role: "admin",
    createdAt: new Date("2025-01-01"),
  },
  {
    id: "2",
    name: "Mike Chen",
    email: "mike@company.com",
    role: "sales_rep",
    createdAt: new Date("2025-01-01"),
  },
  {
    id: "3",
    name: "Emily Rodriguez",
    email: "emily@company.com",
    role: "sales_rep",
    createdAt: new Date("2025-01-01"),
  },
]

// Mock leads
export const mockLeads: Lead[] = [
  {
    id: "1",
    firstName: "John",
    lastName: "Smith",
    email: "john.smith@techcorp.com",
    phone: "+1 555-0101",
    company: "TechCorp Inc",
    jobTitle: "CTO",
    status: "qualified",
    source: "website",
    score: 85,
    assignedTo: "2",
    tags: ["enterprise", "hot-lead"],
    customFields: {},
    createdAt: new Date("2026-01-01"),
    updatedAt: new Date("2026-01-05"),
  },
  {
    id: "2",
    firstName: "Emma",
    lastName: "Wilson",
    email: "emma.wilson@startup.io",
    phone: "+1 555-0102",
    company: "Startup.io",
    jobTitle: "Founder",
    status: "contacted",
    source: "referral",
    score: 72,
    assignedTo: "3",
    tags: ["startup", "saas"],
    customFields: {},
    createdAt: new Date("2026-01-02"),
    updatedAt: new Date("2026-01-04"),
  },
  {
    id: "3",
    firstName: "Michael",
    lastName: "Brown",
    email: "m.brown@enterprise.com",
    phone: "+1 555-0103",
    company: "Enterprise Solutions",
    jobTitle: "VP of Sales",
    status: "new",
    source: "email_campaign",
    score: 45,
    assignedTo: "2",
    tags: ["enterprise"],
    customFields: {},
    createdAt: new Date("2026-01-06"),
    updatedAt: new Date("2026-01-06"),
  },
  {
    id: "4",
    firstName: "Lisa",
    lastName: "Anderson",
    email: "lisa.a@digitalagency.com",
    phone: "+1 555-0104",
    company: "Digital Agency",
    jobTitle: "Marketing Director",
    status: "qualified",
    source: "social_media",
    score: 68,
    assignedTo: "3",
    tags: ["marketing", "smb"],
    customFields: {},
    createdAt: new Date("2026-01-03"),
    updatedAt: new Date("2026-01-05"),
  },
]

// Mock deals
export const mockDeals: Deal[] = [
  {
    id: "1",
    title: "TechCorp Enterprise License",
    leadId: "1",
    stage: "proposal",
    value: 50000,
    probability: 75,
    expectedCloseDate: new Date("2026-02-15"),
    assignedTo: "2",
    createdAt: new Date("2026-01-05"),
    updatedAt: new Date("2026-01-05"),
  },
  {
    id: "2",
    title: "Startup.io Monthly Subscription",
    leadId: "2",
    stage: "negotiation",
    value: 12000,
    probability: 60,
    expectedCloseDate: new Date("2026-02-01"),
    assignedTo: "3",
    createdAt: new Date("2026-01-04"),
    updatedAt: new Date("2026-01-04"),
  },
  {
    id: "3",
    title: "Digital Agency Package",
    leadId: "4",
    stage: "contact",
    value: 25000,
    probability: 40,
    expectedCloseDate: new Date("2026-03-01"),
    assignedTo: "3",
    createdAt: new Date("2026-01-05"),
    updatedAt: new Date("2026-01-05"),
  },
]

// Mock activities
export const mockActivities: Activity[] = [
  {
    id: "1",
    type: "call",
    leadId: "1",
    userId: "2",
    subject: "Initial discovery call",
    description: "Discussed requirements and budget. Very interested in enterprise features.",
    completedAt: new Date("2026-01-05T10:00:00"),
    priority: "high",
    createdAt: new Date("2026-01-05T10:00:00"),
    updatedAt: new Date("2026-01-05T10:00:00"),
  },
  {
    id: "2",
    type: "email",
    leadId: "2",
    userId: "3",
    subject: "Follow-up email with proposal",
    description: "Sent detailed proposal and pricing information.",
    completedAt: new Date("2026-01-04T14:30:00"),
    priority: "medium",
    createdAt: new Date("2026-01-04T14:30:00"),
    updatedAt: new Date("2026-01-04T14:30:00"),
  },
  {
    id: "3",
    type: "task",
    leadId: "3",
    userId: "2",
    subject: "Send welcome package",
    dueDate: new Date("2026-01-07T09:00:00"),
    priority: "medium",
    createdAt: new Date("2026-01-06T16:00:00"),
    updatedAt: new Date("2026-01-06T16:00:00"),
  },
  {
    id: "4",
    type: "meeting",
    leadId: "1",
    userId: "2",
    subject: "Product demo scheduled",
    dueDate: new Date("2026-01-08T15:00:00"),
    priority: "high",
    createdAt: new Date("2026-01-05T11:00:00"),
    updatedAt: new Date("2026-01-05T11:00:00"),
  },
]

// Mock dashboard metrics
export const mockDashboardMetrics: DashboardMetrics = {
  totalLeads: 247,
  qualifiedLeads: 89,
  conversionRate: 36,
  averageDealValue: 28500,
  totalRevenue: 485000,
  leadsThisMonth: 42,
  dealsWonThisMonth: 8,
  pipelineValue: 387000,
}
